version: '3'

services:
  mysql-service:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: vinaperfumeapp
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  discovery-service:
    image: truongtanphat6302/discovery-service
    restart: unless-stopped
    ports:
      - "8761:8761"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-gateway:
    image: truongtanphat6302/api-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - discovery-service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  image-service:
   image: truongtanphat6302/image-service
   restart: unless-stopped
   ports:
     - "8201:8201"
   depends_on:
     - discovery-service
   extra_hosts:
     - "host.docker.internal:host-gateway"

  product-service:
   image: truongtanphat6302/product-service
   restart: unless-stopped
   ports:
     - "8001:8001"
   depends_on:
     - mysql-service
     - discovery-service
   extra_hosts:
     - "host.docker.internal:host-gateway"

  order-service:
   image: truongtanphat6302/order-service
   restart: unless-stopped
   ports:
     - "8101:8101"
   depends_on:
     - mysql-service
     - discovery-service
   extra_hosts:
     - "host.docker.internal:host-gateway"

  # webapp:
  #  image: truongtanphat6302/webapp
  #  restart: unless-stopped
  #  ports:
  #    - "80:80"
  #  depends_on:
  #    - discovery-service
  #  extra_hosts:
  #    - "host.docker.internal:host-gateway"
